name: Deploy to EC2

on:
  push:
    branches:
      - main
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: npm install
      
           
      - name: Copy files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "."  # Path to your project files
          target: "/home/ubuntu/E-commerece-SaaS-Project"  
      
      # - name: SSH into EC2 instance and deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #    host: ${{ secrets.EC2_HOST }}
      #    username: ${{ secrets.EC2_USERNAME }}
      #    key: ${{ secrets.EC2_PRIVATE_KEY }}
      #    port: 22
      #    script: |
      #             cd /path/to/destination  # Change to your project directory
      #             npm install --production  # Install only production dependencies
      #             pm2 restart app.js  # Restart your Node.js application (you might need to adjust this command)
      
      

    
  
  


  

